source("code/header.R")
source("code/questions.R")
source("code/delete_trash_questions.R")
source("code/link_responses_to_questions.R")
source("code/mc_question_functions.R")
source("code/questions_into_blocks.R")
knit('report.rnw', output = 'latex/report.tex')
setwd('./latex')
tools::texi2pdf('report.tex', clean = TRUE)
