\documentclass{article}
\setlength\parindent{0pt}
\begin{document}

<<run-all, include=FALSE>>=
library(knitr)
blocks_latex = NULL
for (i in 1:length(Blocks[[1]]$Payload)) {
  blocks_latex = c(blocks_latex, knit_expand('block_template.rnw'))
  for (j in 1:length(Blocks[[1]]$Payload[[i]]$BlockElements)) {
    blocks_latex = c(blocks_latex, knit_expand('question_template.rnw'))
  }
}
@

\Sexpr{paste(knit(text = blocks_latex), collapse = '\n')}

\end{document}
